"""add contrast to image_uploads

Revision ID: 6509a40e6c11
Revises: c1d2e3f4a5b6
Create Date: 2026-06-28 17:24:46.591278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6509a40e6c11'
down_revision: Union[str, Sequence[str], None] = 'c1d2e3f4a5b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default backfills any existing row with the neutral 1.0 multiplier;
    # the app always writes an explicit value, so the default is only needed here.
    op.add_column(
        'image_uploads',
        sa.Column('contrast', sa.Float(), nullable=False, server_default='1.0'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image_uploads', 'contrast')
    # ### end Alembic commands ###
