"""add ha_connections

Revision ID: b95cfc578ce1
Revises: 93ae96650c94
Create Date: 2026-06-28 15:17:48.345609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b95cfc578ce1'
down_revision: Union[str, Sequence[str], None] = '93ae96650c94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ha_connections',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('ingest_token', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_ha_connections_ingest_token'), 'ha_connections', ['ingest_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ha_connections_ingest_token'), table_name='ha_connections')
    op.drop_table('ha_connections')
    # ### end Alembic commands ###
